<?php
    if ( ! defined( 'ABSPATH' ) ) exit;

    function countryIsoToCountry($code) {
        $code = strtoupper($code);
        if ($code == 'AD') return "Andorra";
        if ($code == 'AE') return "Vereinigte Arabische Emirate";
        if ($code == 'AF') return "Afghanistan";
        if ($code == 'AG') return "Antigua und Barbuda";
        if ($code == 'AI') return "Anguilla";
        if ($code == 'AL') return "Albanien";
        if ($code == 'AM') return "Armenien";
        if ($code == 'AO') return "Angola";
        if ($code == 'AR') return "Argentinien";
        if ($code == 'AS') return "Amerikanisch-Samoa";
        if ($code == 'AT') return "Österreich";
        if ($code == 'AU') return "Australien";
        if ($code == 'AW') return "Aruba";
        if ($code == 'AZ') return "Aserbaidschan";
        if ($code == 'BA') return "Bosnien und Herzegowina";
        if ($code == 'BB') return "Barbados";
        if ($code == 'BD') return "Bangladesch";
        if ($code == 'BE') return "Belgien";
        if ($code == 'BF') return "Burkina Faso";
        if ($code == 'BG') return "Bulgarien";
        if ($code == 'BH') return "Bahrain";
        if ($code == 'BI') return "Burundi";
        if ($code == 'BJ') return "Benin";
        if ($code == 'BM') return "Bermuda";
        if ($code == 'BN') return "Brunei";
        if ($code == 'BO') return "Bolivien";
        if ($code == 'BR') return "Brasilien";
        if ($code == 'BS') return "Bahamas";
        if ($code == 'BT') return "Bhutan";
        if ($code == 'BW') return "Botsuana";
        if ($code == 'BY') return "Weißrussland";
        if ($code == 'BZ') return "Belize";
        if ($code == 'CA') return "Kanada";
        if ($code == 'CD') return "Demokratische Republik Kongo";
        if ($code == 'CF') return "Zentralafrikanische Republik";
        if ($code == 'CG') return "Republik Kongo";
        if ($code == 'CH') return "Schweiz";
        if ($code == 'CI') return "Elfenbeinküste";
        if ($code == 'CK') return "Cookinseln";
        if ($code == 'CL') return "Chile";
        if ($code == 'CM') return "Kamerun";
        if ($code == 'CN') return "China";
        if ($code == 'CO') return "Kolumbien";
        if ($code == 'CR') return "Costa Rica";
        if ($code == 'CU') return "Kuba";
        if ($code == 'CV') return "Kap Verde";
        if ($code == 'CW') return "Curaçao";
        if ($code == 'CY') return "Zypern";
        if ($code == 'CZ') return "Tschechien";
        if ($code == 'DE') return "Deutschland";
        if ($code == 'DJ') return "Dschibuti";
        if ($code == 'DK') return "Dänemark";
        if ($code == 'DM') return "Dominica";
        if ($code == 'DO') return "Dominikanische Republik";
        if ($code == 'DZ') return "Algerien";
        if ($code == 'EC') return "Ecuador";
        if ($code == 'EE') return "Estland";
        if ($code == 'EG') return "Ägypten";
        if ($code == 'EH') return "Westsahara";
        if ($code == 'ER') return "Eritrea";
        if ($code == 'ES') return "Spanien";
        if ($code == 'ET') return "Äthiopien";
        if ($code == 'FI') return "Finnland";
        if ($code == 'FJ') return "Fidschi";
        if ($code == 'FK') return "Falklandinseln";
        if ($code == 'FM') return "Mikronesien";
        if ($code == 'FO') return "Färöer";
        if ($code == 'FR') return "Frankreich";
        if ($code == 'GA') return "Gabun";
        if ($code == 'GB') return "Vereinigtes Königreich";
        if ($code == 'GD') return "Grenada";
        if ($code == 'GE') return "Georgien";
        if ($code == 'GG') return "Guernsey";
        if ($code == 'GH') return "Ghana";
        if ($code == 'GI') return "Gibraltar";
        if ($code == 'GL') return "Grönland";
        if ($code == 'GM') return "Gambia";
        if ($code == 'GQ') return "Äquatorialguinea";
        if ($code == 'GR') return "Griechenland";
        if ($code == 'GS') return "Südgeorgien und die Südlichen Sandwichinseln";
        if ($code == 'GT') return "Guatemala";
        if ($code == 'GV') return "Guinea";
        if ($code == 'GY') return "Guyana";
        if ($code == 'HN') return "Honduras";
        if ($code == 'HR') return "Kroatien";
        if ($code == 'HT') return "Haiti";
        if ($code == 'HU') return "Ungarn";
        if ($code == 'ID') return "Indonesien";
        if ($code == 'IE') return "Irland";
        if ($code == 'IL') return "Israel";
        if ($code == 'IM') return "Insel Man";
        if ($code == 'IN') return "Indien";
        if ($code == 'IO') return "Britisches Territorium im Indischen Ozean";
        if ($code == 'IQ') return "Irak";
        if ($code == 'IR') return "Iran";
        if ($code == 'IS') return "Island";
        if ($code == 'IT') return "Italien";
        if ($code == 'JE') return "Jersey";
        if ($code == 'JM') return "Jamaika";
        if ($code == 'JO') return "Jordanien";
        if ($code == 'JP') return "Japan";
        if ($code == 'KE') return "Kenia";
        if ($code == 'KG') return "Kirgisistan";
        if ($code == 'KH') return "Kambodscha";
        if ($code == 'KI') return "Kiribati";
        if ($code == 'KM') return "Komoren";
        if ($code == 'KN') return "St. Kitts und Nevis";
        if ($code == 'KP') return "Nordkorea";
        if ($code == 'KR') return "Südkorea";
        if ($code == 'KW') return "Kuwait";
        if ($code == 'KY') return "Kaimaninseln";
        if ($code == 'KZ') return "Kasachstan";
        if ($code == 'LA') return "Laos";
        if ($code == 'LB') return "Libanon";
        if ($code == 'LC') return "St. Lucia";
        if ($code == 'LI') return "Liechtenstein";
        if ($code == 'LK') return "Sri Lanka";
        if ($code == 'LR') return "Liberia";
        if ($code == 'LS') return "Lesotho";
        if ($code == 'LT') return "Litauen";
        if ($code == 'LU') return "Luxemburg";
        if ($code == 'LV') return "Lettland";
        if ($code == 'LY') return "Libyen";
        if ($code == 'MA') return "Marokko";
        if ($code == 'MC') return "Monaco";
        if ($code == 'MD') return "Moldawien";
        if ($code == 'ME') return "Montenegro";
        if ($code == 'MG') return "Madagaskar";
        if ($code == 'MH') return "Marshallinseln";
        if ($code == 'MK') return "Nordmazedonien";
        if ($code == 'ML') return "Mali";
        if ($code == 'MM') return "Myanmar";
        if ($code == 'MN') return "Mongolei";
        if ($code == 'MR') return "Mauretanien";
        if ($code == 'MS') return "Montserrat";
        if ($code == 'MT') return "Malta";
        if ($code == 'MU') return "Mauritius";
        if ($code == 'MV') return "Malediven";
        if ($code == 'MW') return "Malawi";
        if ($code == 'MX') return "Mexiko";
        if ($code == 'MY') return "Malaysia";
        if ($code == 'MZ') return "Mosambik";
        if ($code == 'NA') return "Namibia";
        if ($code == 'NE') return "Niger";
        if ($code == 'NG') return "Nigeria";
        if ($code == 'NI') return "Nicaragua";
        if ($code == 'NL') return "Niederlande";
        if ($code == 'NO') return "Norwegen";
        if ($code == 'NP') return "Nepal";
        if ($code == 'NR') return "Nauru";
        if ($code == 'NU') return "Niue";
        if ($code == 'NZ') return "Neuseeland";
        if ($code == 'OM') return "Oman";
        if ($code == 'PA') return "Panama";
        if ($code == 'PE') return "Peru";
        if ($code == 'PG') return "Papua-Neuguinea";
        if ($code == 'PH') return "Philippinen";
        if ($code == 'PK') return "Pakistan";
        if ($code == 'PL') return "Polen";
        if ($code == 'PN') return "Pitcairn";
        if ($code == 'PS') return "Palästinensische Autonomiegebiete";
        if ($code == 'PT') return "Portugal";
        if ($code == 'PU') return "Guinea-Bissau";
        if ($code == 'PW') return "Palau";
        if ($code == 'PY') return "Paraguay";
        if ($code == 'QA') return "Katar";
        if ($code == 'RO') return "Rumänien";
        if ($code == 'RS') return "Serbien";
        if ($code == 'RU') return "Russland";
        if ($code == 'RW') return "Ruanda";
        if ($code == 'SA') return "Saudi-Arabien";
        if ($code == 'SB') return "Salomonen";
        if ($code == 'SC') return "Seychellen";
        if ($code == 'SD') return "Sudan";
        if ($code == 'SE') return "Schweden";
        if ($code == 'SG') return "Singapur";
        if ($code == 'SH') return "St. Helena, Ascension und Tristan da Cunha";
        if ($code == 'SI') return "Slowenien";
        if ($code == 'SK') return "Slowakei";
        if ($code == 'SL') return "Sierra Leone";
        if ($code == 'SM') return "San Marino";
        if ($code == 'SN') return "Senegal";
        if ($code == 'SO') return "Somalia";
        if ($code == 'SR') return "Surinam";
        if ($code == 'SS') return "Südsudan";
        if ($code == 'ST') return "São Tomé und Príncipe";
        if ($code == 'SV') return "El Salvador";
        if ($code == 'SX') return "St. Martin (Niederlande)";
        if ($code == 'SY') return "Syrien";
        if ($code == 'SZ') return "Eswatini";
        if ($code == 'TC') return "Turks- und Caicosinseln";
        if ($code == 'TD') return "Tschad";
        if ($code == 'TG') return "Togo";
        if ($code == 'TH') return "Thailand";
        if ($code == 'TJ') return "Tadschikistan";
        if ($code == 'TK') return "Tokelau";
        if ($code == 'TL') return "Osttimor";
        if ($code == 'TM') return "Turkmenistan";
        if ($code == 'TN') return "Tunesien";
        if ($code == 'TO') return "Tonga";
        if ($code == 'TR') return "Türkei";
        if ($code == 'TT') return "Trinidad und Tobago";
        if ($code == 'TV') return "Tuvalu";
        if ($code == 'TW') return "Taiwan";
        if ($code == 'TZ') return "Tansania";
        if ($code == 'UA') return "Ukraine";
        if ($code == 'UG') return "Uganda";
        if ($code == 'US') return "USA";
        if ($code == 'UY') return "Uruguay";
        if ($code == 'UZ') return "Usbekistan";
        if ($code == 'VA') return "Staat Vatikanstadt";
        if ($code == 'VC') return "Saint Vincent und die Grenadinen";
        if ($code == 'VE') return "Venezuela";
        if ($code == 'VG') return "Britische Jungferninseln";
        if ($code == 'VN') return "Vietnam";
        if ($code == 'VU') return "Vanuatu";
        if ($code == 'WS') return "Samoa";
        if ($code == 'XK') return "Kosovo";
        if ($code == 'YE') return "Jemen";
        if ($code == 'ZA') return "Südafrika";
        if ($code == 'ZM') return "Sambia";
        if ($code == 'ZW') return "Simbabwe";
    }
